---
title: "Série Temporelle"
subtitle: "Master 1 MAS Rennes - Série Temporelle"
author: "Dylan"
geometry: margin=2.5cm
lang: "fr-FR"
documentclass: article
classoption: a4paper
urlcolor: "blue"
fontsize: "11pt"
date: "15 mai 2020"
output:
  pdf_document:
    toc: true
    toc_depth: 2
    number_sections: true
  html_notebook:
    df_print: paged
    highlight: tango
    theme: cerulean
jupyter:
  jupytext:
    formats: ipynb,Rmd
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.1'
      jupytext_version: 1.2.4
  kernelspec:
    display_name: R
    language: R
    name: ir
---

\pagenumbering{gobble}
\newpage
\pagenumbering{arabic} 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}
library(tidyverse)
library(ggfortify)
```

# Import des données

```{r message=FALSE, warning=FALSE}
period <-
  seq(as.Date('1969-01-01'), as.Date('1984-12-31'), by = "month")

ukdeath <- 
  read_delim("../data.txt", delim = "  ", col_types = "if") %>%
  mutate(death_log = log(death),
         period = period)
```

```{r echo=FALSE}
summary(ukdeath)
```

```{r echo=FALSE, fig.width=8, message=FALSE, warning=FALSE}
ggplot(ukdeath) +
  aes(x = period, y = death, color = law) +
  geom_point() + geom_line() + stat_smooth(method = "loess") +
  labs(title = "Nombre de morts sur les accidents de la route") +
  theme(plot.title = element_text(hjust = 0.5))
```

```{r echo=FALSE, fig.width=8, message=FALSE, warning=FALSE}
ggplot(ukdeath) +
  aes(x = period, y = death_log, color = law) +
  geom_point() + geom_line() + stat_smooth(method = "loess") +
  labs(title = "Nombre de morts sur les accidents de la route (au log)") +
  theme(plot.title = element_text(hjust = 0.5))
```

# Lagplots

```{r}
ukdeath$death_log %>% lag.plot(., lags = 16)
ukdeath$death_log %>% monthplot(., ylab = "Décès", xlab = "Mois")
```

# Trouver la période et le degré

## La période (`lag`)

```{r}
Lag_Mean <- NULL
Lag_Var <- NULL

for (ind in 1:36) {
  diff <- diff(ukdeath$death_log, ind, 1)
  Lag_Mean[ind] <- abs(mean(diff))
  Lag_Var[ind] <- var(diff)
}

ggplot() + aes(y = Lag_Mean, x = 1:36) + geom_point()
ggplot() + aes(y = Lag_Var, x = 1:36) + geom_point()
```

## Le degré (`differencies`)

```{r}
Dif_Mean <- NULL
Dif_Var <- NULL

for (ind in 1:12) {
  diff <- diff(ukdeath$death_log, 12, ind)
  Dif_Mean[ind] <- abs(mean(diff))
  Dif_Var[ind] <- var(diff)
}

ggplot() + aes(y = Dif_Mean, x = 1:12) + geom_point()
ggplot() + aes(y = Dif_Var, x = 1:12) + geom_point()
```

# A choisir

lag : 12
diff : 1 ou 2

```{r}
exemple <- diff(ukdeath$death_log, 12 , 2)
acf(exemple, 24)
```

# Reprod

```{r}
t <- 1:192
sinusoides <- t %o% c(rep(1:5, 2)) * pi / 6
sinusoides[, 1:5] <- sin(sinusoides[, 1:5])
sinusoides[, 6:10] <- cos(sinusoides[, 6:10])
sinusoides <- as.data.frame(sinusoides)
names(sinusoides) <-
  c(paste("sin_", 1:5, sep = ""), paste("cos_", 1:5, sep = ""))
```

```{r}
log_death <- ukdeath$death_log
df <- data.frame(log_death, t, t ^ 2, t ^ 3)
df <- cbind(df, sinusoides)
ModAddifitf <- lm(data = df, log_death ~ .)
summary(ModAddifitf)
```


```{r}
plot(ModAddifitf)
plot(ModAddifitf$residuals)
t.test(ModAddifitf$residuals)
acf(ModAddifitf$residuals, 192)
```

