---
title: "Coronavirus"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: united
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
```
```{r global, include=FALSE}
source('scripts/global.R')
```

# Situation mondiale

Column {data-width=650}
-----------------------------------------------------------------------

### Nombre de cas

```{r}
renderPlotly(
  worldmap <- latest() %>% 
    plot_ly(
      lat = ~Lat,
      lon = ~Long,
      marker = list(color = 'red', size = ~log(Cas), sizeref=0.1, opacity=0.4),
      type = 'scattermapbox',
      hovertext = ~State) %>%
    layout(
      mapbox = list(
        style = 'carto-positron',
        zoom = 1.2,
        center = list(lon = 18, lat= 35)),
      margin = list(
        l = 0, r = 0,
        b = 0, t = 0,
        pad = 0
      )
    )
)

```

Column {data-width=350}
-----------------------------------------------------------------------

### Données

```{r}
DT::renderDT(
  DT::datatable(
    brief('Country'),
    options = list(pageLength = 5)
    )
  )
```

### Chart C

```{r}

```

