---
title: "Cyberattaques des smartphones"
author: "Loïc Rakotoson"
output:
  html_notebook:
    df_print: paged
    highlight: tango
    theme: flatly
jupyter:
  jupytext:
    formats: ipynb,Rmd
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.1'
      jupytext_version: 1.2.4
  kernelspec:
    display_name: R
    language: R
    name: ir
---


```{r}
options(warn = -1)
library(tidyverse)
library(caret)
library(randomForest)
library(ranger) #RandomForest plus rapide
library(rpart)
library(pROC)
```

```{r}
df <- read_csv("data/Attempt 8.csv")
```

```{r}
df <- df %>% 
  mutate_at(c('Destination IP', 'Protocol', 'Label'), funs(factor))
```

```{r}
ggplot(df) + 
  aes(x = Label) + geom_bar(aes(y = (..count..)/sum(..count..))) + 
  facet_grid(.~Protocol) +
  theme(axis.text.x=element_text(angle=90, hjust=1))
```

```{r}
length(unique(df$`Destination Port`))
```

```{r}
ip_split <- function(ip){
    ipMain <- paste(str_split(ip, "\\.")[[1]][1], str_split(ip, "\\.")[[1]][2], sep = ".")
    return(ipMain)
}

```

```{r}
df %>%
select(IP = `Destination IP`) %>% rowwise() %>% mutate(sub_label = paste(str_split(`IP`, "\\.")[[1]][1], str_split(`IP`, "\\.")[[1]][2], sep = "."))
```

```{r}
df  %>% 
group_by(`Destination IP`) %>% 
summarise(n = n()) %>% 
top_n(20)
```

```{r}
df  %>% 
group_by(`Source Port`) %>% 
summarise(n = n()) %>% 
top_n(10)
```

```{r}
df  %>% 
group_by(`Destination Port`) %>% 
summarise(n = n()) %>% 
top_n(10)
```

```{r}
ggplot(df %>% mutate(`Destination Port` = as.factor(`Destination Port`))) +
  aes(x = `Destination Port`) + geom_bar() + #facet_grid(.~Label) +
  theme(axis.text.x=element_text(angle=90, hjust=1))
```

